---
- name: restart yanic
  service:
    name: yanic
    state: restarted
    
- name: restart ffbs-polld
  service:
    name: ffbs-polld
    state: restarted

- name: reload systemd
  command: systemctl daemon-reload
