---
- name: Install required packages
  become: true
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - nginx
- name: Create nginx default snippet directory
  become: true
  file:
    path: "/etc/nginx/site-default.d"
    state: directory
- name: Create nginx default config
  template:
    src: "default.j2"
    dest: "/etc/nginx/sites-available/default"
