- name: Install python development packages
  apt:
    state: latest
    default_release: testing
    name:
      - python3.7
      - python3.7-venv
      - python3-pip
- name: Synchronize python-dev
  become: false
  synchronize:
    src: python-dev/
    dest: /vagrant/python-dev/
    delete: yes
    recursive: yes
- name: Prepare venv
  become: false
  command: "/vagrant/python-dev/setup.sh"
