- name: Install python development packages
  apt: name={{ item }} state=latest default_release=testing
  with_items:
    - python3.6
    - python3.6-venv
    - python3-pip
- name: Synchronize python-dev
  become: false
  synchronize:
    src: python-dev/
    dest: /vagrant/python-dev/
    delete: yes
    recursive: yes
- name: Prepare venv
  become: false
  command: "/vagrant/python-dev/setup.sh"
