- name: Install monitoring-plugins-basic
  apt: name=monitoring-plugins-basic state=latest
- name: Add icinga user
  user: name=icinga-node
- name: Add ssh key
  authorized_key: user=icinga-node
                  manage_dir=yes
                  key='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAwZ2N+tAX6lh+D94GE0POchF+ikXK6+7rPpqmmPLnso+Fw0hRApaghWR4vpXVxAPXQbbRUrETEVC6FMuZP+xya1ZEu5PovSNtYOsN5h4O3uEzz0qPXKk9dMpQCpXUZkD6GYN0cO7lysJSq55oZ8cVEmrE+P0GcU5FpCXj/9oFPLGd+WKvTw+b6VPz2Y+vIVjjUwWq8uBaFPGeNa7UgEKtZLSy5duc+UbBnvwFZFD7I/T/ydzfU5c38AX7Biimdqw2un0GgbZXJghw/vbd+xuWDBH/aotUwn5/JvJNI6rIdFO0cb97O92HG09HAYo5x6qXUhGEVCPubk/mUqLOCYCH nagios@sarumon'
                  key_options='no-agent-forwarding,no-pty,no-user-rc,no-X11-forwarding'

