- name: Add influxdb key
  apt_key:
    id: 684A14CF2582E0C5
    url: https://repos.influxdata.com/influxdb.key

- name: Add repository
  apt_repository:
    repo: 'deb [arch=amd64] https://repos.influxdata.com/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} stable'

- name: Install influxdb
  apt:
    name:
      - influxdb
      - influxdb-client

- name: Configure influxdb
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify: restart influxdb

- name: Flush Handlers
  meta: flush_handlers

- name: Prepare influxdb ffbs
  shell: |
    influx -execute 'CREATE DATABASE ffbs'
    influx -execute 'ALTER RETENTION POLICY autogen ON ffbs DURATION 366d DEFAULT'

- name: Prepare influxdb collectd
  shell: |
    influx -execute 'CREATE DATABASE collectd'
    influx -execute 'ALTER RETENTION POLICY autogen ON collectd DURATION 7d DEFAULT'
    influx -execute 'CREATE RETENTION POLICY month ON collectd DURATION 31d REPLICATION 1'
    influx -execute 'CREATE RETENTION POLICY year ON collectd DURATION 366d REPLICATION 1'
    influx -execute 'CREATE CONTINUOUS QUERY "cq_month" ON "collectd" BEGIN SELECT mean(value) as value INTO "collectd"."month".:MEASUREMENT FROM /.*/ GROUP BY time(300s),* END'
    influx -execute 'CREATE CONTINUOUS QUERY "cq_year" ON "collectd" BEGIN SELECT mean(value) as value INTO "collectd"."year".:MEASUREMENT FROM /.*/ GROUP BY time(21600s),* END'
