- name: Install rsyslog
  apt:
    name:
      - rsyslog

- name: Enable persistent journal
  file:
    path: /var/log/journal
    state: directory

- name: Configure rsyslog
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify: restart rsyslog
