- name: Install collectd
  apt:
    name:
      - collectd
      - libyajl2

- name: Configure collectd
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
  notify: restart collectd
