---
- hosts: all
  become: True
  roles:
    - role: debops.apt_preferences
    - role: debops.apt
    - common
    - wireguard
- hosts: WebServers
  become: True
  roles:
    - nginx
    - firmware-index
- hosts: Concentrators
  become: True
  roles:
    - etcd
- hosts:
  - client
  - concentrator1
  become: True
  roles:
  -  python-dev
