---
- hosts:
  - Concentrators
  tasks:
  - name: Add additional host for exit2 # This is for hosts managed outside of vagrant
    add_host:
      name: 'exit2'
      groups:
      - Backbone
      - Exits
  tags:
  - with_prod
- hosts: all:!UCI-Nodes
  become: True
  roles:
    - users
    - common
    - wireguard
- hosts:
  - Backbone
  strategy: free
  become: True
  roles:
    - vrf
    - bird
    - wireguard-backbone
- hosts:
  - Concentrators
  - WebServers
  - Exits
  become: True
  roles:
    - python-venv
- hosts: etcd_cluster
  become: True
  roles:
    - etcd
- hosts: etcd_clients
  become: True
  roles:
    - etcd-client
- hosts: Concentrators
  become: True
  roles:
    - nginx
    - wireguard-concentrator
    - bind
    - bind-reverse
    - chrony
- hosts: WebServers
  become: True
  roles:
    - nginx
    - firmware-index
    - influxdb
    - grafana
    - yanic
    - meshviewer
- hosts:
  - client
  - concentrator1
  - node1
  become: True
  roles:
  -  python-dev
- hosts:
  - exit1
  become: True
  roles:
    - iptables
    - wireguard-exit
- hosts: Nodes:!UCI-Nodes
  become: True
  roles:
    - vrf
    - python-venv
    - node
    - wireguard-node
    - bridge
    - batman
- hosts: UCI-Nodes
  become: True
  roles:
    - common-uci
    - vrf-uci
    - wireguard
    - wireguard-node-uci
    - batman-uci
    - bridge-uci
