- name: Copy wireguard keys
  copy:
    dest: "/etc/ffbs/{{ item.file }}"
    content: "{{ item.content }}"
  with_items:
    - { file: 'wg-privkey', content: '{{ wg_private_key }}' }
    - { file: 'wg-pubkey', content: '{{ wg_public_key }}' }

- name: Install nodeconfig and noderoute services
  copy:
    src:  "{{ item.name }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { name: 'nodeconfig.init', dest: '/etc/init.d/nodeconfig', mode: '0755' }
    - { name: 'nodeconfig.sh', dest: '/usr/sbin/nodeconfig.sh', mode: '0755'  }
    - { name: 'nodeconfig.lua', dest: '/usr/share/lua/nodeconfig.lua', mode: '0644' }
    - { name: 'noderoute.init', dest: '/etc/init.d/noderoute', mode: '0755' }
    - { name: 'noderoute.lua', dest: '/usr/share/lua/noderoute.lua', mode: '0644' }

- name: Enable and start nodeconfig and noderoute services
  shell: /etc/init.d/{{ item }} enable|| true; /etc/init.d/{{ item }} start
  with_items:
    - nodeconfig
    - noderoute
