- name: Install iptables-persistent package
  apt: name=iptables-persistent state=present

- name: Configure IPv4 firewall
  template:
    src: 'iptables.j2'
    dest: '/etc/iptables/rules.v4'
  notify:
  - Reload firewall

- name: Configure IPv6 firewall
  template:
    src: 'ip6tables.j2'
    dest: '/etc/iptables/rules.v6'
  notify:
  - Reload firewall
