- name: Install bird package
  apt: name=bird state=present
- name: Configure bird (v4)
  template:
    src: "bird.conf.j2"
    dest: "/etc/bird/bird.conf"
    owner: "root"
    group: "bird"
    mode: "0640"
  notify:
    - Reload bird
- name: Configure bird (v6)
  template:
    src: "bird6.conf.j2"
    dest: "/etc/bird/bird6.conf"
    owner: "root"
    group: "bird"
    mode: "0640"
  notify:
    - Reload bird6
- name: Enable routing
  sysctl:
    name:  "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    sysctl_file: "/etc/sysctl.d/10-routing.conf"
  with_items:
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.ipv6.conf.all.forwarding', value: '1' }
    - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
    - { name: 'net.ipv6.conf.all.accept_redirects', value: '0' }
