- name: Install bird package
  apt: name=bird state=present
- name: Configure bird
  template:
    src: "bird.conf.j2"
    dest: "/etc/bird/bird.conf"
    owner: "root"
    group: "bird"
    mode: "0640"
  notify:
    - Reload bird
- name: Configure bird
  template:
    src: "bird6.conf.j2"
    dest: "/etc/bird/bird6.conf"
    owner: "root"
    group: "bird"
    mode: "0640"
  notify:
    - Reload bird6
