---
- name: Install dehydrated
  apt:
    name:
    - dehydrated
    state: present
    update_cache: yes
  notify:
  - Register dehydrated
- name: Create hook.sh
  template:
    src: "hook.sh.j2"
    dest: "/etc/dehydrated/hook.sh"
    mode: 0755
- name: Enable hook
  lineinfile:
    path: /etc/dehydrated/config
    regexp: "^HOOK="
    line: "HOOK=/etc/dehydrated/hook.sh"
  notify:
  - Run dehydrated
- name: Create cronjob
  copy:
    src: 'dehydrated'
    dest: '/etc/cron.weekly/'
    mode: 0755
