- name: enable website-extras timer
  service:
    name: website-extras.timer
    daemon-reload: true
    enabled: true
    state: started

- name: reload nginx
  service:
    name: nginx
    state: reloaded
