- name: Create wireguard configuration
  template:
    src: 'wireguard.j2'
    dest: '/etc/wireguard/{{ hostvars[item].wg_peer_ifname }}.conf'
  with_items: '{{ groups.Concentrators }}'

- name: Create wireguard interfaces
  template:
    src: 'interface.j2'
    dest: '/etc/network/interfaces.d/{{ hostvars[item].wg_peer_ifname }}'
  with_items: '{{ groups.Concentrators }}'
  notify:
  - Activate concentrator interfaces

- name: Install node systemd service
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'node-route.service', dest: '/etc/systemd/system/', mode: 644 }

- name: Enable and start node-route.service
  systemd:
    daemon_reload: yes
    name: node-route.service
    state: started
    enabled: yes
