---
- name: Install required packages
  become: true
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - git
- name: Configurate firmware anycase address on the vrf
  copy:
    src:  'vrf.conf'
    dest: '/etc/systemd/system/nginx.service.d/'
    mode: 0644
- name: Configure nginx anycast
  become: true
  template:
    src: nginx-anycast.conf.j2
    dest: /etc/nginx/site-default.d/20-anycast.conf
  notify:
    - Reload nginx
- name: Configure nginx location
  become: true
  template:
    src: nginx-location.conf.j2
    dest: /etc/nginx/site-default.d/50-firmware.conf
  notify:
    - Reload nginx
- name: Install from git
  become: true
  git:
    repo: 'https://github.com/ffbs/freifunk-firmware-index.git'
    dest: /var/www/firmware
