- name: Create bridge configuration
  shell: |
    if ! uci -q show network.br0 > /dev/null; then
      uci set network.br0=interface
    fi
    uci set network.br0.ifname='bat0 eth2'
    uci set network.br0.type=bridge
    uci set network.br0.proto=none

    uci changes

    uci commit
  register: uci_bridge
  changed_when: "uci_bridge.stdout"
- name: Restart network
  when: uci_bridge.changed
  command: "/etc/init.d/network restart"
