- name: Install etcd packages
  apt: name={{ item }} state=present default_release=unstable
  with_items:
    - etcd-client
    - etcd-server
  register:
    etcd_install
- name: Enable etcd service
  command: "systemctl enable etcd"
  when: etcd_install.changed
- name: Configure etcd
  template:
    src: "etcd.j2"
    dest: "/etc/default/etcd"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart etcd
- name: Make etcd v3 API the default
  copy:
    dest: "/etc/profile.d/etcd.sh"
    content: "export ETCDCTL_API=3\n"
