- name: Create wireguard configuration
  template:
    src: 'wireguard.j2'
    dest: '/etc/wireguard/{{ hostvars[item].wg_peer_ifname }}.conf'
  with_items: '{{ groups.Concentrators | difference([inventory_hostname])}}'

- name: Create wireguard interfaces
  template:
    src: 'interface.j2'
    dest: '/etc/network/interfaces.d/{{ hostvars[item].wg_peer_ifname }}'
  with_items: '{{ groups.Concentrators | difference([inventory_hostname])}}'
  notify:
  - Activate network interfaces
