- name: Configure routing protocol name
  lineinfile:
    dest: "/etc/iproute2/rt_protos"
    line: "23\tfreifunk"
- name: Configure routing table name
  lineinfile:
    dest: "/etc/iproute2/rt_tables"
    line: "10\tfreifunk"
- name: Configure sysctl for vrf
  sysctl:
    name:  "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    sysctl_file: "/etc/sysctl.d/20-vrf.conf"
  with_items:
    #  keep IPv6 global addresses as VRF enslavement changes
    - { name: 'net.ipv6.conf.all.keep_addr_on_down', value: '1' }
    # we want etcd and ssh to be accessible from all VRFs
    - { name: 'net.ipv4.tcp_l3mdev_accept', value: '1' }
    # we don't need udp ports accessible from all VRFs
    - { name: 'net.ipv4.udp_l3mdev_accept', value: '0' }

