- name: Install python development packages
  apt:
    state: latest
    default_release: testing
    name:
      - python3.7
      - python3.7-venv
      - python3-pip
- name: Create /srv/venv
  shell: "python3.7 -m venv /srv/venv"
  args:
    creates: "/srv/venv"
- name: Synchronize python-dev
  become: false
  synchronize:
    src: python-dev/
    dest: /vagrant/python-dev/
    delete: yes
    recursive: yes
- name: Prepare /srv/venv
  shell: |
    . /srv/venv/bin/activate

    cd /vagrant/python-dev
    pip install --upgrade .
