# {{ ansible_managed }}
[respondd]
enable           = {{ yanic_respondd | ternary('true','false') }}
#synchronize      = "1m"
collect_interval = "{{ yanic_respondd_collect_interval }}"

[[respondd.interfaces]]
#ifname          = "{{ yanic_respondd_interface }}"
ifname          = "lo"
ip_address      = "::1"
send_no_request = true
port            = 11001

[webserver]
enable  = {{ yanic_webserver | ternary('true','false') }}
bind    = "{{ yanic_webserver_bind }}"
webroot = "{{ yanic_webserver_webroot }}"

[nodes]
state_path     = "{{ yanic_nodes_state_path }}"
save_interval  = "{{ yanic_nodes_save_interval }}"
offline_after  = "{{ yanic_nodes_offline_after }}"
prune_after    = "{{ yanic_nodes_prune_after }}"

[[nodes.output.meshviewer]]
enable     = {{ yanic_meshviewer | ternary('true','false') }}
version    = {{ yanic_meshviewer_version }}
nodes_path = "{{ yanic_meshviewer_nodes }}"
graph_path = "{{ yanic_meshviewer_graph }}"

[[nodes.output.meshviewer-ffrgb]]
enable = true
path   = "/srv/yanic/pub/meshviewer.json"

[database]
delete_after    = "{{ yanic_database_delete_after }}"
delete_interval = "{{ yanic_database_delete_interval }}"

{% for db in yanic_influxdb %}
[[database.connection.influxdb]]
enable   = {{ db.enable | ternary('true','false') }}
address  = "{{ db.host }}"
database = "{{ db.database }}"
username = "{{ db.username }}"
password = "{{ db.password }}"
{% endfor %}

{% for db in yanic_socket %}
[[database.connection.socket]]
enable   = {{ db.enable | ternary('true','false') }}
type     = "{{ db.type }}"
address = "{{ db.address }}"
{% endfor %}

[[database.connection.logging]]
enable   = false
path     = "/srv/yanic/var/yanic.log"
