- name: Install batman packages
  opkg: name={{ item }} state=present update_cache=yes
  with_items:
    - batctl
- name: Load batman modules
  shell: |
    modprobe cfg80211 || true
    modprobe batman-adv || true
- name: Create batman configuration
  shell: |
    if ! uci -q show network.mesh > /dev/null; then
      uci set network.mesh=interface
    fi
    uci set network.mesh.ifname=eth1
    uci set network.mesh.proto=batadv
    uci set network.mesh.mesh=bat0

    if ! uci -q show network.bat0 > /dev/null; then
      uci set network.bat0=interface
    fi
    uci set network.bat0.ifname=bat0
    uci set network.bat0.proto=static
    uci set network.bat0.mtu=1500

    uci changes

    uci commit
  register: uci_batman
  changed_when: "uci_batman.stdout"
- name: Restart network
  when: uci_batman.changed
  command: "/etc/init.d/network restart"
