- name: Add users
  user:
    name: "{{ item.name }}"
    groups: []
    shell: "/bin/bash"
  with_items: "{{ ffbs_admins }}"

- name: Add authorized keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh }}"
  with_items: "{{ ffbs_admins }}"

- name: Allow sudo access without password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ item.name }} ALL="
    line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  with_items: "{{ ffbs_admins }}"
