- name: Configurate chrony anycase address on the vrf
  copy:
    src:  'vrf.conf'
    dest: '/etc/systemd/system/chrony.service.d/'
    mode: 0644
- name: Install chrony package
  apt: name=chrony state=present
- name: Configure chrony
  template:
    src: "chrony.conf.j2"
    dest: "/etc/chrony/chrony.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart chrony
