---
- name: Activate backbone interfaces
  become: true
  command: ifup {{ hostvars[item].wg_peer_ifname }}
  with_items: '{{ groups.Concentrators | union(groups.Exits) | difference([inventory_hostname])}}'
