- name: Install node packages
  apt: name={{ item }} state=present
  with_items:
    - dnsmasq
    - batctl
    - bridge-utils

- name: Copy nodeconfig certificate
  copy:
    src:  "node-config-pub.key"
    dest: "/etc/ffbs/"
