- import_tasks: ../../common/tasks/hosts.yml

- name: Install lua util module
  copy:
    src:  "util.lua"
    dest: "/usr/share/lua/"

- name: Copy nodeconfig certificate
  copy:
    src:  "node-config-pub.key"
    dest: "/etc/ffbs/"
