---
- name: Create website-extras folder
  file:
    path: /var/www/website-extras
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: Copy api.json template
  copy:
    src: "api.json.template"
    dest: "/var/www/website-extras/api.json.template"
    mode: 0644
    owner: www-data
    group: www-data
    
- name: Copy website-extras cron script
  copy:
    src: "cron.sh"
    dest: "/var/www/website-extras/cron.sh"
    mode: 0755
    owner: www-data
    group: www-data
    
- name: Install website-extras timer unit
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
  - website-extras.service
  - website-extras.timer
  notify: enable website-extras timer

- name: Configure nginx location for master
  vars:
    branch: "master"
  template:
    src: nginx-location.conf.j2
    dest: /etc/nginx/site-default.d/50-website.conf
  notify: reload nginx

- name: Create nginx testbed snippet directory
  file:
    path: "/etc/nginx/site-testbed.d"
    state: directory

- name: Configure nginx location for testbed
  vars:
    branch: "testbed"
  template:
    src: nginx-location.conf.j2
    dest: /etc/nginx/site-testbed.d/50-website.conf
  notify: reload nginx

- name: Create nginx config for testbed
  template:
    src: "testbed.j2"
    dest: "/etc/nginx/sites-available/testbed"

- name: Activate nginx config for testbed
  file:
    src: /etc/nginx/sites-available/testbed
    dest: /etc/nginx/sites-enabled/testbed
    state: link
  notify:
    - Reload nginx
