---
- name: Build hosts file
  become: true
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{ item }}" state=present
  when: '"ansible_host" in hostvars[item] and item != ansible_hostname'
  with_items: "{{ groups['all'] }}"
