---
- name: Build hosts file
  become: true
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_ssh_host }} {{ item }}" state=present
  when: item != ansible_hostname
  with_items: "{{ groups['all'] }}"
