---
- name: Install required packages
  become: true
  apt: name=yarnpkg state=present

- name: Create users
  user:
    name: meshviewer
    home: "{{meshviewer_home}}"
    #generate_ssh_key: yes
    #ssh_key_type: rsa
    #ssh_key_file: .ssh/id_rsa
    #ssh_key_comment: "meshviewer@{{inventory_hostname}}"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: meshviewer
  with_items:
  - "{{ meshviewer_path_src }}"
  - "{{ meshviewer_path_bin }}"

- name: Enable acl support for rootfs
  command: "mount -o remount,acl /"

- name: Install meshviewer
  become: true
  become_user: meshviewer
  include: install.yml

- name: Configure nginx location
  template:
    src: nginx-location.conf.j2
    dest: /etc/nginx/site-default.d/50-meshviewer.conf
  notify: Reload nginx
