- name: Create ffbs forward zone
  template:
    src: "db.ffbs.j2"
    dest: "/etc/bind/db.ffbs"
  notify:
    - Reload bind zones
- name: Enable ffbs forward zone
  become: true
  lineinfile:
    dest: "/etc/bind/named.conf.local"
    regexp: '^zone "ffbs"'
    line: 'zone "ffbs" { type master; file "/etc/bind/db.ffbs"; };'
    state: present
  notify:
    - Reload bind zones
- name: Create RPZ zone
  template:
    src: "db.rpz.j2"
    dest: "/etc/bind/db.rpz"
  notify:
    - Reload bind zones
- name: Enable RPZ zone
  become: true
  lineinfile:
    dest: "/etc/bind/named.conf.local"
    regexp: '^zone "rpz"'
    line: 'zone "rpz" { type master; file "/etc/bind/db.rpz"; };'
    state: present
  notify:
    - Reload bind zones
