- name: Create wireguard configuration
  template:
    src: 'wireguard.j2'
    dest: '/etc/wireguard/wg-nodes.conf'
  register:
    wg_nodes_conf

- name: Create wireguard interfaces
  template:
    src: 'interface.j2'
    dest: '/etc/network/interfaces.d/wg-nodes'
  notify:
  - Activate network interfaces

- name: Reconfigure wireguard
  when: wg_nodes_conf.changed
  command: wg setconf wg-nodes /etc/wireguard/wg-nodes.conf
