- name: Create wireguard configuration
  template:
    src: 'wireguard.j2'
    dest: '/etc/wireguard/wg-nodes.conf'
  notify:
  - Reconfigure wg-nodes

- name: Create wireguard interfaces
  template:
    src: 'interface.j2'
    dest: '/etc/network/interfaces.d/wg-nodes'
  notify:
  - Activate network interfaces
