- name: Install concentrator services
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'etcd-config-web.service', dest: '/etc/systemd/system/', mode: 644 }
    - { src: 'concentrator-route.service', dest: '/etc/systemd/system/', mode: 644 }
    - { src: 'concentrator-config.service', dest: '/etc/systemd/system/', mode: 644 }

- name: Copy nodeconfig certificates
  copy:
    src:  "{{ item }}"
    dest: "/etc/ffbs/"
  with_items:
    - 'node-config-priv.key'
    - 'node-config-pub.key'

- name: Enable and start systemd service
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - etcd-config-web.service
    - concentrator-route.service
    - concentrator-config.service

- name: Install nginx concentrator config
  template:
    src: nginx-location.conf.j2
    dest: /etc/nginx/site-default.d/50-concentrator.conf
  notify:
    - Reload nginx
