- name: Install concentrator services
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'etcd-config-web.service', dest: '/etc/systemd/system/', mode: 644 }
    - { src: 'concentrator-route.service', dest: '/etc/systemd/system/', mode: 644 }

- name: Copy nodeconfig certificates
  copy:
    src:  "{{ item }}"
    dest: "/etc/ffbs/"
  with_items:
    - 'node-config-priv.key'
    - 'node-config-pub.key'

- name: Enable and start etcd-config-web.service
  systemd:
    daemon_reload: yes
    name: etcd-config-web.service
    state: started
    enabled: yes

- name: Enable and start concentrator-route.service
  systemd:
    daemon_reload: yes
    name: concentrator-route.service
    state: started
    enabled: yes
