- name: Configure nginx location
  template:
    src: nginx-location.conf.j2
    dest: /etc/nginx/site-default.d/50-osm.conf

- name: Create nginx cache directory
  file:
    path: /var/cache/nginx/osm
    state: directory
    mode: 0700
    owner: www-data
    group: root

- name: Configure nginx cache
  template:
    src: nginx-cache.conf.j2
    dest: /etc/nginx/conf.d/osm-cache.conf

- name: Reload nginx
  become: true
  service: name=nginx state=reloaded
