---
- name: Install required packages
  become: true
  apt: name=golang state=present

- name: Create users
  user:
    name: yanic
    home: "{{yanic_home}}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_file: .ssh/id_rsa
    ssh_key_comment: "yanic@{{inventory_hostname}}"

- name: Install yanic
  shell: go get -u github.com/FreifunkBremen/yanic
  environment:
    GOPATH: "{{yanic_home}}"
  notify:
    - restart yanic

- name: Configure yanic
  template:
    src: config.toml
    dest: /etc/yanic.conf
  notify:
    - restart yanic

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: yanic
  with_items:
  - "{{ yanic_meshviewer_path }}"
  - "{{ yanic_var_path }}"

- name: Install system units
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'yanic.service', dest: '/etc/systemd/system/', mode: 644 }
    - { src: 'ffbs-polld.service', dest: '/etc/systemd/system/', mode: 644 }
  notify:
    - reload systemd
    - restart yanic
    - restart ffbs-polld

- name: Enable yanic
  service:
    name: yanic
    enabled: yes

- name: Configure nginx location
  template:
    src: nginx-location.conf.j2
    dest: /etc/nginx/site-default.d/50-yanic.conf

