- name: Automatically load batman-adv module
  lineinfile:
    dest: "/etc/modules"
    line: "batman-adv"
- name: Configure bat0 interface
  template:
    src: "interface.j2"
    dest: "/etc/network/interfaces.d/20-bat0"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
  - Activate bat0 interface
