- name: Configurate bind9 service startup
  copy:
    src:  'startup.conf'
    dest: '/etc/systemd/system/bind9.service.d/'
    mode: 0644
- name: Confine bind9 to the vrf
  copy:
    src:  'vrf.conf'
    dest: '/etc/systemd/system/bind9.service.d/'
    mode: 0644
- name: Install bind9 package
  apt: name=bind9 state=present
- name: Configure bind9
  template:
    src: "named.conf.options.j2"
    dest: "/etc/bind/named.conf.options"
    owner: "root"
    group: "bind"
    mode: "0640"
  notify:
    - Restart bind9
