- name: Install distro specific wireguard packages
  include_tasks: "{{ distro }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  loop_control:
    loop_var: distro
